version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-baseline-dev
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - ENV=development
      - TZ=Europe/Moscow
    volumes:
      - ./logs:/app/logs
      - .:/app
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
